/** @type {import("tailwindcss").Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background:             "#F6F7F8",
        foreground:             "#202124",
        card:                   "#FFFFFF",
        "card-foreground":      "#202124",
        primary:                "#43B8C9",
        "primary-foreground":   "#FFFFFF",
        secondary:              "transparent",
        "secondary-foreground": "#505862",
        muted:                  "#EEEFF1",
        "muted-foreground":     "#B0B7BF",
        accent:                 "#008489",
        "accent-foreground":    "#FFFFFF",
        destructive:            "#CA3F32",
        "destructive-hover":    "#AD3021",
        border:                 "#D2D6DA",
        "border-hover":         "#B0B7BF",
        input:                  "#FFFFFF",
        ring:                   "#2E92A1",
        "background-hover":     "#F1FAFB",
        selected:               "#E9F5F9",
        "selected-hover":       "#C6E9EF",
        tooltip:                "#32383E",
        "tooltip-foreground":   "#FFFFFF",
        "icon-default":         "#505862",
        "icon-hover":           "#008489",
        "status-error":         "#CA3F32",
        "status-warning":       "#FFA940",
        "status-success":       "#5ABD4A",
        "status-info":          "#0684F9",
        "status-error-bg":      "#FDEDED",
        "status-warning-bg":    "#FFF4E5",
        "status-success-bg":    "#EDF7ED",
        "status-info-bg":       "#E9F5F9",
        sidebar:                "#2A394A",
        "sidebar-foreground":   "#FFFFFF",
        "sidebar-primary":      "#2E92A1",
        "sidebar-accent":       "#485767",
        "sidebar-border":       "#505862",
        gray: {
          50:  "#F6F7F8",
          100: "#EEEFF1",
          200: "#D2D6DA",
          300: "#B0B7BF",
          400: "#B0B7BF",
          500: "#505862",
          600: "#505862",
          700: "#202124",
          800: "#202124",
          900: "#202124",
        },
      },
      boxShadow: {
        sm:        "0px 2px 4px rgba(16,18,20,0.1)",
        dropdown:  "4px 4px 16px 0px rgba(16,18,20,0.1)",
        header:    "0px 1px 8px 0px rgba(16,18,20,0.1)",
      },
      borderRadius: {
        button: "4px",
        card:   "8px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
}
